# Generated by Django 4.2 on 2023-04-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_validation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
