# Generated by Django 4.2 on 2023-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_validation', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
